name: pypython
channels:
  - conda-forge
  - default
dependencies:
  - numba>=0.53.1
  - numpy>=1.20.2
  - psutil>=5.8.0
  - SQLAlchemy>=1.4.15
  - matplotlib>=3.3.4
  - pandas>=1.2.4
  - scipy>=1.6.3
  - astropy>=4.2.1
  - black>=22.8.0
  - isort>=5.10.1
  - docformatter>=1.5.0
  - pylint>=2.14.5
  - dust_extinction>=1.1
